apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storageos-daemonset
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-logs-container: storageos
    spec:
      containers:
      - args:
        - server
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: BOOTSTRAP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: storageos-api
        - name: BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: storageos-api
        - name: ADVERTISE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: storageos-node-config
            optional: false
        image: storageos-node
        imagePullPolicy: IfNotPresent
        name: storageos
        ports:
        - containerPort: 5705
          hostPort: 5705
          name: api
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /dev/fuse
          name: fuse
        - mountPath: /sys
          name: sys
        - mountPath: /var/lib/storageos
          mountPropagation: Bidirectional
          name: state
        - mountPath: /etc/storageos
          name: config
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /dev
          name: device-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=/var/lib/kubelet/plugins_registry/storageos/csi.sock
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: csi-node-driver-registrar
        imagePullPolicy: IfNotPresent
        name: csi-driver-registrar
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/lib/csi/sockets/
          name: registrar-socket-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --probe-timeout=3s
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        image: csi-livenessprobe
        imagePullPolicy: IfNotPresent
        name: csi-liveness-probe
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPID: true
      initContainers:
      - env:
        - name: DAEMONSET_NAME
          value: storageos-daemonset
        - name: DAEMONSET_NAMESPACE
          value: default
        envFrom:
        - configMapRef:
            name: storageos-node-config
            optional: false
        image: storageos-init
        imagePullPolicy: IfNotPresent
        name: storageos-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: kernel-modules
          readOnly: true
        - mountPath: /sys
          mountPropagation: Bidirectional
          name: sys
        - mountPath: /var/lib/storageos
          mountPropagation: Bidirectional
          name: state
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccountName: storageos-daemonset-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node.kubernetes.io/disk-pressure
        operator: Exists
      - key: node.kubernetes.io/memory-pressure
        operator: Exists
      - key: node.kubernetes.io/network-unavailable
        operator: Exists
      - key: node.kubernetes.io/not-ready
        operator: Exists
      - key: node.kubernetes.io/pid-pressure
        operator: Exists
      - key: node.kubernetes.io/unreachable
        operator: Exists
      - key: node.kubernetes.io/unschedulable
        operator: Exists
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: kernel-modules
      - hostPath:
          path: /dev/fuse
          type: ""
        name: fuse
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /var/lib/storageos
          type: ""
        name: state
      - configMap:
          name: storageos-node-config
          optional: false
        name: config
      - hostPath:
          path: /var/lib/kubelet/device-plugins/
          type: DirectoryOrCreate
        name: registrar-socket-dir
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/storageos
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
  updateStrategy:
    type: OnDelete
