name: Publish develop image

on:
  push:
    branches:
      - main

env:
  MANIFEST_LIST: storageos/operator:develop
  AMD_IMG: storageos/operator:develop-amd64
  ARM64_IMG: storageos/operator:develop-arm64
  ARM_IMG: storageos/operator:develop-arm

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: --snapshot --rm-dist --config .github/.goreleaser-develop.yaml --skip-validate
      - name: Push container image
        run: |
          docker push ${{ env.AMD_IMG }}
          docker push ${{ env.ARM64_IMG }}
          docker push ${{ env.ARM_IMG }}
      - name: Create and publish manifest list
        run: |
          docker manifest create ${{ env.MANIFEST_LIST }} \
            ${{ env.AMD_IMG }} ${{ env.ARM64_IMG }} ${{ env.ARM_IMG }}
          docker manifest push ${{ env.MANIFEST_LIST }}
